# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(856, 540)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.centralwidget.setFont(font)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 852, 472))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit_file_dir = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_file_dir.setMaximumSize(QtCore.QSize(999, 30))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_file_dir.setFont(font)
        self.lineEdit_file_dir.setObjectName("lineEdit_file_dir")
        self.horizontalLayout_2.addWidget(self.lineEdit_file_dir)
        self.Button_select_file = QtWidgets.QPushButton(self.widget)
        self.Button_select_file.setMinimumSize(QtCore.QSize(80, 0))
        self.Button_select_file.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Button_select_file.setFont(font)
        self.Button_select_file.setObjectName("Button_select_file")
        self.horizontalLayout_2.addWidget(self.Button_select_file)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.comboBox_select_sheet = QtWidgets.QComboBox(self.widget)
        self.comboBox_select_sheet.setMaximumSize(QtCore.QSize(999, 30))
        self.comboBox_select_sheet.setObjectName("comboBox_select_sheet")
        self.horizontalLayout.addWidget(self.comboBox_select_sheet)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setMaximumSize(QtCore.QSize(80, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.pic_label = QtWidgets.QLabel(self.widget)
        self.pic_label.setMinimumSize(QtCore.QSize(850, 350))
        self.pic_label.setObjectName("pic_label")
        self.gridLayout.addWidget(self.pic_label, 2, 0, 1, 1)
        self.Button_start = QtWidgets.QPushButton(self.widget)
        self.Button_start.setObjectName("Button_start")
        self.gridLayout.addWidget(self.Button_start, 3, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 856, 27))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Button_select_file.setText(_translate("MainWindow", "选择文件"))
        self.label.setText(_translate("MainWindow", "选择sheet"))
        self.pic_label.setText(_translate("MainWindow", "TextLabel"))
        self.Button_start.setText(_translate("MainWindow", "开始处理并保存至csv文件"))
